### PR TITLE
Support locate of unknown tags/albums in media library

### PR DESCRIPTION
**Pull request by trygveaa**
This adds support for locating a song in the media library, when the tag or album (for respectively three and two column mode) is unknown. I.e. the tag or album was not listed in the list of all tags or albums.

This is desirable when using a MPD server that is not able to give a complete list of tags or albums. This may be the case for e.g. streaming servers which does not have a list of the complete library.

One example of this is Mopidy with Mopidy-Spotify. It is not possible to give a complete list of the artists available in Spotify, and you often load tracks with artists that is not listed by list/listallinfo. This makes the locate song in media library work for such tracks.

### CODE REVIEW

**Comment by IvanMalison** [comment]
What is the status of this pr?

**Comment by arybczak** [comment]
I'm not sure. I'm a bit reluctant to include this, as the manipulations it does are a little tricky.

**Comment by arybczak** [comment]
Ok, let's give it a shot. @trygveaa , if you're still interested in getting this merged, could you fix the conflicts and make one commit out of it? Also, please use comments to indicate in appropriate places that this is specifically for mopidy, because if there will be no such comment, someone eventually will break it by accident.

**Comment by trygveaa** [comment]
Great, thanks. I'll do that.

**Comment by trygveaa** [comment]
I have merged master, fixed the conflicts and added comments now.

**Comment by arybczak** [comment]
I squashed commits, added more comments (copied from your intermediate commit descriptions), made w few small changes and merged the patch. Sorry that it took so long.

**Pull request closed without merging**
