### PR TITLE
Changes API for directories creation.

### LINKED ISSUE #336: [BUG][minor] Crashes if `lyrics_directory` is under a not yet created directory
ncmpcpp doesn't start if `lyrics_directory` is inside an nonexistent directory.

----

If you have `lyrics_directory = ~/.cache/ncmpcpp/lyrics`, but no `ncmpcpp` in `.cache`, it crashes.
However, it doesn't if `~/.cache/ncmpcpp` exists, and the path `~/.cache/ncmpcpp/lyrics` is created.

### PR DESCRIPTION
**Pull request by sticken88**
This should fix #336

### CODE REVIEW

**Comment by arybczak** [comment]
Can you explain why that change would help?

**Comment by sticken88** [comment]
Because that API takes care of directories creation if they don't exist. If `lyrics_directory` is set to a path with a non existing directory in it the API will create it properly preventing any crash.
DO you agree?

**Comment by arybczak** [comment]
> Because that API takes care of directories creation if they don't exist.

I'm confused. `boost::filesystem::create_directory` surely also does that? Also, you modified the line with `ncmpcpp_directory`, not `lyrics_directory`.

**Comment by sticken88** [comment]
> I'm confused. boost::filesystem::create_directory surely also does that?
`boost::filesystem::create_directory` takes care of just one directory, while `boost::filesystem::create_directories` parses the path provided and creates a directory for each subdirectory found in that path. I understand this from the documentation. 

You are right. If you agree with the change I can create another pull request by changing the proper line.

**Comment by buzuck** [comment]
Thanks for this PR.
I would have changed both lines as well. You cannot make any assumption about the user's configuration. In the issue I opened, `lyrics_directory` was indeed in `ncmpcpp_directory`, but that may not always be the case.

**Comment by sticken88** [comment]
> In the issue I opened (#336), lyrics_directory was indeed in ncmpcpp_directory, but that may not always be the case.

I agree.

**Comment by larson-carter** [comment]
Can someone give me an update on why this is necessary? @buzuck or @sticken88

**Comment by sticken88** [comment]
> Can someone give me an update on why this is necessary? @buzuck or @sticken88

I believe it's necessary because ncmpcpp crashes if the path in `lyrics_directory` does not exist. I think it would be better to use `boost::filesystem::create_directories` in order to create the directories which don't exist.

**Comment by larson-carter** [comment]
I'm going to pause this until someone else can test on a different distro other than Ubutnu. @sticken88 can you test on another distro?

**Comment by buzuck** [comment]
Indeed, ncmpcpp crashes in the parent of `lyrics_directory` doesn't exist.

If `lyrics_directory = /tmp/doesnt/exists`, and `/tmp/doesnt/` does not exist, here is the log message wielded: 

```
Reading configuration from /home/fol/.config/ncmpcpp/config...
Error while processing configuration: boost::filesystem::create_directory: No such file or directory: "/tmp/doesnt/exists"
````
However, if `lyrics_directory = /tmp/doesnt` exists, ncmpcpp starts and creates `/tmp/doesnt/exists` without any issue.

Tested on Archlinux.

**Pull request merged**
