### PR TITLE
Added support for genius.com lyrics

### PR DESCRIPTION
**Pull request by nytopop**
Added support for fetching lyrics from genius.com as per the suggestion in issue #52.
Uses a GoogleLyricsFetcher.

### CODE REVIEW

**Comment by arybczak** [comment]
Does it work well? I think this project offers api, which should possibly have a higher success rate that using google?

**Comment by nytopop** [comment]
Genius does offer an API, but it requires auth to use. Wouldn't be too hard to implement, but users would need to create an account at genius and pass the api secret to ncmpcpp somehow, probably conf file.

I've been using the google fetcher since I made the pull request, I haven't seen any obvious problems as far as finding / formatting lyrics. But you're right, the api would probably be a better option. 

On a side note, if using the fetch lyrics in background feature and you skip songs often, google will often blacklist / require captcha and break all of the google fetchers.

**Comment by arybczak** [comment]
> Genius does offer an api, but it requires auth to use. Wouldn't be too hard to implement, but users would need to create an account at genius and pass the api secret to ncmpcpp somehow, probably conf file.

I think you can just create one account and have ncmpcpp store the api secret? That's how last.fm integration works.

> On a side note, if using the fetch lyrics in background feature and you skip songs often, google will often blacklist / require captcha and break all of the google fetchers.

Hmm, I don't think anything apart from slowing down the requests frequency can be done to remedy that.

**Comment by arybczak** [comment]
308c2be2f6401bc12e976ead6a1e21871abf7d6a (regex version had to be readjusted).

**Comment by arybczak** [comment]
> On a side note, if using the fetch lyrics in background feature and you skip songs often, google will often blacklist / require captcha and break all of the google fetchers.

This should also be solved, lyrics in background are no longer fetched in parallel.

**Comment by anthonyrom** [comment]
Hey just wanted to say I'd really appreciate Genius lyrics functionality. nytopop's implementation looks good to me, and is a lot simpler than going the API route (which would admittedly be better but would be a good bit more involved)

**Pull request closed without merging**
