### PR TITLE
Add a README, showing enable visualizer

### PR DESCRIPTION
**Pull request by BlitzKraft**
Even though I used ncmpcpp for a long time, after installing it on a new computer, I struggled for hours trying to find how to enable the visualizer. And also found many users across many forums asking the same. 

I thought it would be helpful if it is right here in the readme. Most of the file's contents are from [here](http://rybczak.net/ncmpcpp/). Added markdown for decoration and specified the example options.

### CODE REVIEW

**Comment by arybczak** [comment]
If anything, README should redirect to http://rybczak.net/ncmpcpp/ - it doesn't make sense for this information to be duplicated.

**Comment by BlitzKraft** [comment]
Done. Added a link to http://rybczak.net/ncmpcpp/ at the beginning.

**Comment by arybczak** [comment]
What I meant that the majority if info is a duplication of stuff at http://rybczak.net/ncmpcpp/ and it simply shouldn't be there.

**Comment by arybczak** [comment]
README should ONLY reference that link and then there should be stuff you need. Let me know what info is missing from the webpage and I'll add it.

**Comment by BlitzKraft** [comment]
Ah. I couldn't find on the site that visualizer is disabled by default and that it needs to be explicitly specified during compile. I went through searching in forums for an hour or two before I realized what needs to be done. After that it was quick and easy.

**Pull request merged**
