### PR TITLE
bindings: Support a bindings file in $XDG_CONFIG_HOME/ncmpcpp

### PR DESCRIPTION
**Pull request by mineo**
Fixes https://github.com/arybczak/ncmpcpp/issues/91.

This also rewrites the intro in doc/bindings to be more like doc/config.

### CODE REVIEW

**Comment by mineo** [comment]
@arybczak Hey, I was just wondering if you have any feedback for this pull request (even if it's just "I haven't looked at it yet" ;-) ).

**Comment by arybczak** [comment]
Hey, sorry for not providing any feedback for so long.

The patch is good code-wide, but I'm not sure what is its purpose. Can you describe when is it useful?

**Comment by mineo** [comment]
As described in https://github.com/arybczak/ncmpcpp/issues/91#issuecomment-165207887, it's useful because it allows storing both the general configuration file as well as the bindings file of ncmpcpp in a single directory, instead of having one `~/.ncmpcpp` and the other in `~/.config/ncmpcpp`.

**Comment by arybczak** [comment]
Merged, thanks.

**Comment by musoke** [comment]
Thanks @mineo and @arybczak !

**Pull request closed without merging**
