### PR TITLE
Added a fully working 'Album-only' view

### PR DESCRIPTION
**Pull request by Polochon-street**
It shows up after toggling a second time the album view (by pressing '4' two times).
Not sure where to show this in the help though.

### CODE REVIEW

**Comment by soredake** [comment]
@arybczak

**Comment by khogeland** [comment]
@Polochon-street Thanks a ton for this addition, dealing with VA releases was a huge pain before.

**Comment by soredake** [comment]
@arybczak

**Comment by Polochon-street** [comment]
Hey, any progress on that? That would be cool to have that feature by default

**Comment by tgy** [comment]
i'm waiting for this too! would be very helpful

**Comment by onodera-punpun** [comment]
I'd like too see this merged as well :)

**Comment by Berulacks** [comment]
Any update on this? Would really love to see this added

**Comment by jonnieey** [comment]
waiting for this feature too

**Pull request merged**
