### PR TITLE
Need a little help with this one

### PR DESCRIPTION
**Pull request by djvs**
Almost have it, this "quick sort" method, which just sorts using the default prefix without all the typing.  However I got a little stuck on one last little thing, which is why the range doesn't get set to every mitem being true before the sort - you have to select the range and THEN do ctrl-v for it to work.

Also I set the SortPlaylistDialogWhatever->sort() to public instead of private, so it could be accessed by this method.  

I really like this idea and it was close to what was there in a previous version so LMK...

Apologize for any poor coding...just mimicking what's there.

### CODE REVIEW

**Comment by arybczak** [comment]
What are you trying to do?

**Comment by djvs** [comment]
A one-keystroke (ctrl-v) select-all, sort playlist with default fields order, unselect all.

**Comment by djvs** [comment]
Oh - looks like I also have the change in default fields order I have on my branch.

**Comment by arybczak** [comment]
You don't have to modify the code, put this in your bindings file:

```
def_key "alt-s"
  require_screen "playlist"
  remove_selection
  reverse_selection
  sort_playlist
  move_end
  scroll_up
  press_enter
  remove_selection
```

Then alt-s will do what you want (although keep in mind that I'll lift range restriction from sorting soon, so fiddling with selection won't be needed).

**Comment by djvs** [comment]
That sort of works, although it's a hefty configuration option for a user.  You could consider adding my action and then adding to the configuration a way to add default sort fields maybe.  That would be a cool feature, "sort by my default sort" with one key combo.  Just an idea.

**Comment by arybczak** [comment]
What does "sort of" mean in this context?

**Comment by djvs** [comment]
Well, in the context of letting users do a quick sort.  It works but only after being specified by the user in the bindings file.

**Comment by arybczak** [comment]
Range requirement was lifted.

**Pull request closed without merging**
